services:
  app:
    build: .
    container_name: bpy_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    # command: python3 -c "import bpy;"
    # command: pip debug --verbose
    ports:
      - 80:80
    volumes:
      - .:/src